## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np

In [12]:
y_matrix=[[1,2,3],[4,5,6],[7,8,9]] #inter number
x=np.array(y_matrix) #make matrix (x)
d_matrix=[[1,4,5],[5,6,7],[9,10,11]] #inter numbers
g=np.array(y_matrix) #make matrix (g)
x*g #multiplication matrix x and g



array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Write a NumPy program to compute the determinant of a given square array

In [15]:
y_matrix=[[1,2,3,4,5,6,7,8,9]] #inter numbers
arr=np.array(y_matrix) #make matrix (arr)
np.sqrt(arr) #to find square array

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
        2.44948974, 2.64575131, 2.82842712, 3.        ]])

## Write a NumPy program to compute the cross product of two given vectors

In [16]:
y_matrix=[[1,2],[3,1]] #inter number
x=np.array(y_matrix) #make matrix (x)
d_matrix=[[1,5],[2,4]] #inter numbers
g=np.array(y_matrix) #make matrix (g)
f=np.cross(x,g)#cross product of two vectors(x,g)
f



array([0, 0])

## Write a NumPy program to compute the condition number of a given matrix

In [19]:
y_matrix=[[1,2],[7,8]] #inter number
x=np.array(y_matrix) #make matrix (x)
d=np.cond(x) #the condition number of matrix
d

AttributeError: module 'numpy' has no attribute 'cond'

## Write a NumPy program to compute the inverse of a given matrix

In [31]:
y_matrix=[[1,2],[7,8]] #inter number
x=np.array(y_matrix) #make matrix (x)
x 


array([[1, 2],
       [7, 8]])

In [32]:
l=np.inv(x) #inverse of amatrix(x)
l

AttributeError: module 'numpy' has no attribute 'inv'